apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - wordpress/wordpress-service.yaml
  - wordpress/wordpress-deployment.yaml
  - wordpress/wordpress-pvc.yaml
  - ../secrets/wordpress-secret.sops.yaml
  
