apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../infrastructure/namespace.yaml
  - databases/
  - applications/

secretGenerator:
  - name: sops-age
    namespace: flux-system
    files:
      - age.agekey=../../age.key
    type: Opaque
