apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mariadb/mariadb-service.yaml
  - mariadb/mariadb-statefulset.yaml
  - mariadb/mariadb-pvc.yaml
  - ../secrets/mariadb-secret.sops.yaml

