apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../applications/wordpress/wordpress-deployment.yaml
  - ../../applications/wordpress/wordpress-service.yaml
  - ../../secrets/wordpress-secret.sops.yaml

generatorOptions:
  disableNameSuffixHash: true
